import type { DataSource, SyncTask, ExchangeItem } from "./types";

export const MOCK_NOW = "2026-08-13 10:30";

export const MOCK_SOURCES: DataSource[] = [
  {
    id: "src-core-pg",
    name: "核心交易 PostgreSQL",
    category: "database",
    subtype: "postgresql",
    status: "available",
    endpoint: "10.24.1.12:5432 / core",
    owner: "张敏",
    config: { host: "10.24.1.12", port: 5432, database: "core", schema: "public", ssl: true, authType: "kerberos" },
    lastTestAt: "2026-08-13 10:25",
    latencyMs: 12,
    tableCount: 47,
    description: "承载交易主链路的核心 OLTP 库，包含订单、支付、退款等业务表。",
    tags: ["核心", "OLTP"],
    updatedAt: MOCK_NOW,
  },
  {
    id: "src-crm-oracle",
    name: "客户 CRM Oracle",
    category: "database",
    subtype: "oracle",
    status: "available",
    endpoint: "10.24.2.8:1521 / CRMDB",
    owner: "陈晨",
    config: { host: "10.24.2.8", port: 1521, database: "CRMDB", schema: "CRM_USER", authType: "basic" },
    lastTestAt: "2026-08-13 10:10",
    latencyMs: 28,
    tableCount: 89,
    description: "客户主数据和营销活动管理。",
    tags: ["客户", "主数据"],
    updatedAt: MOCK_NOW,
  },
  {
    id: "src-order-mysql",
    name: "订单中心 MySQL 集群",
    category: "database",
    subtype: "mysql",
    status: "degraded",
    endpoint: "order-***:3306 / order_center",
    owner: "王磊",
    config: { host: "order-cluster-01", port: 3306, database: "order_center", authType: "basic" },
    lastTestAt: "2026-08-13 09:50",
    latencyMs: 156,
    tableCount: 23,
    description: "订单中心读写分离集群，近期只读延迟偏高。",
    tags: ["订单", "高频"],
    updatedAt: MOCK_NOW,
  },
  {
    id: "src-event-kafka",
    name: "客户事件 Kafka",
    category: "message",
    subtype: "kafka",
    status: "available",
    endpoint: "broker-***:9092 / customer-events",
    owner: "李浩",
    config: { host: "kafka-cluster-03", port: 9092, topic: "customer-events", group: "data-integration", ssl: true, authType: "basic" },
    lastTestAt: "2026-08-13 10:28",
    latencyMs: 5,
    description: "埋点与行为事件实时投递。",
    tags: ["实时", "行为"],
    updatedAt: MOCK_NOW,
  },
  {
    id: "src-marketing-s3",
    name: "营销对象存储 S3",
    category: "object-store",
    subtype: "s3",
    status: "abnormal",
    endpoint: "s3://marketing-***",
    owner: "王雪",
    config: { bucket: "marketing-bucket", path: "campaigns/", authType: "aksk", ssl: true },
    lastTestAt: "2026-08-13 09:15",
    latencyMs: 0,
    description: "营销活动物料和报表文件，S3 bucket 访问权限待续签。",
    tags: ["文件", "待处理"],
    updatedAt: MOCK_NOW,
  },
  {
    id: "src-pay-rest",
    name: "支付平台 REST API",
    category: "api",
    subtype: "rest",
    status: "available",
    endpoint: "https://api.pay-***.com/v3",
    owner: "赵敏",
    config: { baseUrl: "https://api.pay.internal.com/v3", authType: "bearer", ssl: true },
    lastTestAt: "2026-08-13 10:22",
    latencyMs: 89,
    description: "支付交易查询与对账接口。",
    tags: ["支付", "API"],
    updatedAt: MOCK_NOW,
  },
  {
    id: "src-legacy-excel",
    name: "运营报表 SFTP",
    category: "file",
    subtype: "sftp",
    status: "testing",
    endpoint: "sftp://legacy-***:22 /shared/reports",
    owner: "刘洋",
    config: { host: "legacy-sftp", port: 22, path: "/shared/reports", authType: "basic" },
    lastTestAt: "2026-08-13 10:29",
    description: "历史遗留运营部门手工上传的 Excel 报表。",
    tags: ["手工", "遗留"],
    updatedAt: MOCK_NOW,
  },
  {
    id: "src-risk-dameng",
    name: "风险引擎 达梦",
    category: "database",
    subtype: "dameng",
    status: "offline",
    endpoint: "10.24.5.11:5236 / risk_db",
    owner: "周凯",
    config: { host: "10.24.5.11", port: 5236, database: "risk_db", schema: "RISK_USER", authType: "basic" },
    lastTestAt: "2026-08-13 08:00",
    description: "风险评估平台数据库，当前网络隔离中。",
    tags: ["风险", "离线"],
    updatedAt: MOCK_NOW,
  },
];

export const MOCK_SYNC_TASKS: SyncTask[] = [
  {
    id: "sync-trade-cdc",
    name: "交易订单 CDC 入湖",
    mode: "cdc",
    sourceId: "src-core-pg",
    sourceName: "核心交易 PostgreSQL",
    targetType: "hive",
    targetName: "数据湖 ODS 层",
    targetTable: "ods_trade_order",
    schedule: "持续运行",
    owner: "张敏",
    status: "running",
    progress: 72,
    lastRunAt: MOCK_NOW,
    nextRunAt: undefined,
    throughput: 18234,
    recordsTotal: 28400000,
    recordsSynced: 20448000,
    latencyMin: 3,
    retryCount: 0,
    columns: [
      { name: "order_id", type: "bigint", mappedTo: "order_id" },
      { name: "customer_id", type: "bigint", mappedTo: "customer_id" },
      { name: "amount", type: "decimal(18,2)", mappedTo: "order_amount" },
      { name: "status", type: "varchar(20)", mappedTo: "order_status" },
      { name: "created_at", type: "timestamp", mappedTo: "order_time" },
    ],
    logs: [
      { id: "log-1", startedAt: "2026-08-13 10:15", finishedAt: "2026-08-13 10:28", status: "running", recordsRead: 128400, recordsWritten: 128200, durationSec: 780, operator: "system" },
      { id: "log-2", startedAt: "2026-08-13 09:15", finishedAt: "2026-08-13 09:28", status: "success", recordsRead: 140200, recordsWritten: 140200, durationSec: 775, operator: "system" },
      { id: "log-3", startedAt: "2026-08-13 08:15", finishedAt: "2026-08-13 08:29", status: "success", recordsRead: 132800, recordsWritten: 132800, durationSec: 812, operator: "system" },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "sync-customer-full",
    name: "客户主数据全量同步",
    mode: "full",
    sourceId: "src-crm-oracle",
    sourceName: "客户 CRM Oracle",
    targetType: "hive",
    targetName: "数据湖 DWD 层",
    targetTable: "dwd_customer_full",
    schedule: "每日 02:00",
    owner: "陈晨",
    status: "success",
    progress: 100,
    lastRunAt: "2026-08-13 02:18",
    nextRunAt: "2026-08-14 02:00",
    throughput: 0,
    recordsTotal: 4823000,
    recordsSynced: 4823000,
    latencyMin: 12,
    retryCount: 0,
    columns: [
      { name: "CUST_ID", type: "NUMBER(15)", mappedTo: "customer_id" },
      { name: "CUST_NAME", type: "VARCHAR2(100)", mappedTo: "customer_name" },
      { name: "CUST_TYPE", type: "VARCHAR2(20)", mappedTo: "customer_type" },
      { name: "REGISTER_DATE", type: "DATE", mappedTo: "register_date" },
    ],
    logs: [
      { id: "log-4", startedAt: "2026-08-13 02:00", finishedAt: "2026-08-13 02:18", status: "success", recordsRead: 4823000, recordsWritten: 4823000, durationSec: 1080, operator: "system" },
      { id: "log-5", startedAt: "2026-08-12 02:00", finishedAt: "2026-08-12 02:22", status: "success", recordsRead: 4798000, recordsWritten: 4798000, durationSec: 1320, operator: "system" },
      { id: "log-6", startedAt: "2026-08-11 02:00", finishedAt: "2026-08-11 02:20", status: "failed", recordsRead: 2140000, recordsWritten: 2140000, durationSec: 520, errorMessage: "目标端 HDFS 写入超时", operator: "system" },
      { id: "log-7", startedAt: "2026-08-11 02:25", finishedAt: "2026-08-11 02:48", status: "success", recordsRead: 4782000, recordsWritten: 4782000, durationSec: 1380, operator: "system" },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "sync-event-rt",
    name: "客户行为实时入湖",
    mode: "realtime",
    sourceId: "src-event-kafka",
    sourceName: "客户事件 Kafka",
    targetType: "kafka",
    targetName: "Kafka → Flink → Doris",
    targetTable: "dws_customer_event_rt",
    schedule: "持续运行",
    owner: "李浩",
    status: "failed",
    progress: 45,
    lastRunAt: "2026-08-13 09:02",
    nextRunAt: undefined,
    throughput: 284,
    recordsTotal: 1280000,
    recordsSynced: 576000,
    latencyMin: 0,
    retryCount: 3,
    columns: [
      { name: "event_id", type: "string" },
      { name: "user_id", type: "string" },
      { name: "event_type", type: "string" },
      { name: "page_url", type: "string" },
      { name: "ts", type: "timestamp" },
    ],
    logs: [
      { id: "log-8", startedAt: "2026-08-13 09:00", finishedAt: "2026-08-13 09:02", status: "failed", recordsRead: 3200, recordsWritten: 840, durationSec: 120, errorMessage: "Doris sink 写入失败：connection refused at 10.25.3.80:9030", operator: "system" },
      { id: "log-9", startedAt: "2026-08-13 08:50", finishedAt: "2026-08-13 08:55", status: "failed", recordsRead: 8400, recordsWritten: 2100, durationSec: 300, errorMessage: "Doris 节点内存溢出", operator: "system" },
      { id: "log-10", startedAt: "2026-08-13 08:00", finishedAt: "2026-08-13 08:48", status: "success", recordsRead: 684000, recordsWritten: 684000, durationSec: 2880, operator: "system" },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "sync-order-incr",
    name: "订单增量抽取至 Doris",
    mode: "incremental",
    sourceId: "src-order-mysql",
    sourceName: "订单中心 MySQL 集群",
    targetType: "doris",
    targetName: "Doris 实时数仓",
    targetTable: "ods_order_incr",
    schedule: "每 15 分钟",
    owner: "王磊",
    status: "paused",
    progress: 0,
    lastRunAt: "2026-08-13 09:45",
    nextRunAt: "2026-08-13 10:00 (已暂停)",
    throughput: 0,
    recordsTotal: 0,
    recordsSynced: 0,
    latencyMin: 0,
    retryCount: 0,
    logs: [
      { id: "log-11", startedAt: "2026-08-13 09:30", finishedAt: "2026-08-13 09:45", status: "success", recordsRead: 28400, recordsWritten: 28400, durationSec: 900, operator: "王磊" },
      { id: "log-12", startedAt: "2026-08-13 09:15", finishedAt: "2026-08-13 09:25", status: "success", recordsRead: 31200, recordsWritten: 31200, durationSec: 600, operator: "system" },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "sync-pay-rest",
    name: "支付流水 API 拉取",
    mode: "full",
    sourceId: "src-pay-rest",
    sourceName: "支付平台 REST API",
    targetType: "mysql",
    targetName: "支付对账库",
    targetTable: "t_payment_daily",
    schedule: "每日 00:30",
    owner: "赵敏",
    status: "success",
    progress: 100,
    lastRunAt: "2026-08-13 00:48",
    nextRunAt: "2026-08-14 00:30",
    throughput: 0,
    recordsTotal: 128400,
    recordsSynced: 128400,
    latencyMin: 18,
    retryCount: 0,
    columns: [
      { name: "trade_no", type: "varchar(64)" },
      { name: "amount", type: "decimal(18,2)" },
      { name: "channel", type: "varchar(20)" },
      { name: "pay_status", type: "varchar(10)" },
      { name: "pay_time", type: "datetime" },
    ],
    logs: [
      { id: "log-13", startedAt: "2026-08-13 00:30", finishedAt: "2026-08-13 00:48", status: "success", recordsRead: 128400, recordsWritten: 128400, durationSec: 1080, operator: "system" },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "sync-risk-draft",
    name: "风险评分增量（草稿）",
    mode: "incremental",
    sourceId: "src-risk-dameng",
    sourceName: "风险引擎 达梦",
    targetType: "hive",
    targetName: "数据湖 ADS 层",
    targetTable: "ads_risk_score_d",
    schedule: "每日 06:00",
    owner: "周凯",
    status: "draft",
    progress: 0,
    nextRunAt: "2026-08-14 06:00",
    throughput: 0,
    recordsTotal: 0,
    recordsSynced: 0,
    latencyMin: 0,
    retryCount: 0,
    logs: [],
    updatedAt: MOCK_NOW,
  },
];

export const MOCK_EXCHANGES: ExchangeItem[] = [
  {
    id: "ex-customer-profile-api",
    name: "集团客户画像 API",
    channel: "api",
    consumerDept: "集团营销中心",
    consumerContact: "李明 / 138****201",
    sourceSystem: "客户 CRM Oracle",
    frequency: "realtime",
    sla: "99.9% / 500ms",
    dataFormat: "JSON",
    encryption: "TLS 1.3 + HMAC",
    owner: "赵宁",
    status: "published",
    publishedAt: "2026-07-15",
    auditLogs: [
      { id: "a-1", time: "2026-08-13 10:28", consumer: "集团营销中心", action: "调用", result: "成功", records: 1240, latencyMs: 186 },
      { id: "a-2", time: "2026-08-13 10:25", consumer: "集团营销中心", action: "调用", result: "成功", records: 892, latencyMs: 201 },
      { id: "a-3", time: "2026-08-13 10:20", consumer: "集团营销中心", action: "调用", result: "成功", records: 1408, latencyMs: 178 },
      { id: "a-4", time: "2026-08-13 10:15", consumer: "集团营销中心", action: "调用", result: "失败", records: 0, latencyMs: 5000 },
      { id: "a-5", time: "2026-08-13 10:10", consumer: "集团营销中心", action: "调用", result: "成功", records: 1024, latencyMs: 192 },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "ex-regulatory-report",
    name: "监管月报文件交换",
    channel: "file",
    consumerDept: "合规管理部",
    consumerContact: "陈婷 / 139****302",
    sourceSystem: "核心交易 PostgreSQL",
    frequency: "monthly",
    sla: "每月 3 日前",
    dataFormat: "CSV + 数字签名",
    encryption: "AES-256 + 文件签名",
    owner: "王雪",
    status: "submitted",
    auditLogs: [
      { id: "a-6", time: "2026-08-13 08:12", consumer: "合规管理部", action: "下载", result: "成功", records: 1, latencyMs: 120 },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "ex-risk-table-share",
    name: "风险明细库表共享",
    channel: "table",
    consumerDept: "风险管理部",
    consumerContact: "孙磊 / 137****403",
    sourceSystem: "风险引擎 达梦",
    sourceTable: "RISK_DETAIL",
    frequency: "daily",
    sla: "T+1 06:00 前",
    dataFormat: "只读视图 grant",
    encryption: "传输层 SSL",
    owner: "周凯",
    status: "suspended",
    rejectReason: "源端数据库当前离线，需先恢复网络连通",
    auditLogs: [
      { id: "a-7", time: "2026-08-12 23:50", consumer: "风险管理部", action: "查询", result: "失败", records: 0, latencyMs: 30000 },
      { id: "a-8", time: "2026-08-12 23:30", consumer: "风险管理部", action: "查询", result: "失败", records: 0, latencyMs: 30000 },
      { id: "a-9", time: "2026-08-12 06:00", consumer: "风险管理部", action: "查询", result: "成功", records: 28400, latencyMs: 412 },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "ex-product-catalog-api",
    name: "产品目录 API 对外",
    channel: "api",
    consumerDept: "外部合作方 A",
    consumerContact: "对接人 / 白名单 IP",
    sourceSystem: "产品中心",
    frequency: "realtime",
    sla: "99.5% / 800ms",
    dataFormat: "JSON",
    encryption: "mTLS",
    owner: "赵敏",
    status: "published",
    publishedAt: "2026-06-20",
    auditLogs: [
      { id: "a-10", time: "2026-08-13 10:27", consumer: "外部合作方 A", action: "调用", result: "成功", records: 48, latencyMs: 312 },
      { id: "a-11", time: "2026-08-13 10:15", consumer: "外部合作方 A", action: "调用", result: "成功", records: 52, latencyMs: 298 },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "ex-customer-event-msg",
    name: "客户事件消息推送",
    channel: "message",
    consumerDept: "实时推荐系统",
    consumerContact: "事件订阅方",
    sourceSystem: "客户事件 Kafka",
    frequency: "realtime",
    sla: "端到端 ≤ 5s",
    dataFormat: "Avro Schema",
    encryption: "传输层 TLS",
    owner: "李浩",
    status: "approved",
    auditLogs: [
      { id: "a-12", time: "2026-08-13 10:29", consumer: "实时推荐系统", action: "推送", result: "成功", records: 8420, latencyMs: 3200 },
      { id: "a-13", time: "2026-08-13 10:28", consumer: "实时推荐系统", action: "推送", result: "成功", records: 8120, latencyMs: 3100 },
    ],
    updatedAt: MOCK_NOW,
  },
  {
    id: "ex-salary-reject",
    name: "薪酬数据共享（已驳回）",
    channel: "table",
    consumerDept: "外部咨询公司 B",
    consumerContact: "对接人 / 非本公司员工",
    sourceSystem: "人力资源系统",
    sourceTable: "EMP_SALARY",
    frequency: "manual",
    sla: "按需",
    dataFormat: "CSV",
    encryption: "—",
    owner: "刘洋",
    status: "rejected",
    rejectReason: "涉及敏感薪酬 PII 字段，不符合数据安全分级管理要求",
    auditLogs: [],
    updatedAt: MOCK_NOW,
  },
];
