/** Data Asset · mock 使用审计数据：访问明细、异常、整改。 */

import type { Anomaly, AuditEvent, Rectification } from "../types";

/** 场景 H：某 API 一天 1,000 条访问审计（920 成功 / 40 失败 / 30 拒绝 / 10 超时）。 */
function buildGeneratedEvents(): AuditEvent[] {
  const events: AuditEvent[] = [];
  const push = (index: number, result: AuditEvent["result"], extra: Partial<AuditEvent> = {}) => {
    const hour = 8 + Math.floor((index / 1000) * 10);
    const minute = String(index % 60).padStart(2, "0");
    events.push({
      id: `ev-p3-${index}`,
      at: `2026-08-12 ${String(hour).padStart(2, "0")}:${minute}:00`,
      principal: "风控部-风控系统",
      principalKind: "内部系统",
      appId: "app-risk-engine",
      appNameMasked: "风控决策引擎",
      channel: "API",
      ipRegion: "内网-风控区",
      accountMasked: "svc-risk***",
      traceId: `trc-gen-${index}`,
      productId: "p-customer-query-api",
      productName: "客户经营查询 API",
      serviceVersion: 1,
      assetId: "asset-customer-table",
      assetVersion: 2,
      authorizationId: "az-risk-system",
      authorizedPurpose: "贷款风险审核",
      declaredPurpose: "贷款风险审核",
      result,
      ...extra,
    });
  };

  for (let i = 1; i <= 1000; i += 1) {
    if (i <= 920) push(i, "成功", { statusCode: "200", recordCount: 20 + (i % 60), durationMs: 180 + (i % 200) });
    else if (i <= 960) push(i, "失败", { statusCode: "500", errorMasked: "upstream timeout (masked)", durationMs: 1500 + (i % 500) });
    else if (i <= 990) push(i, "拒绝", { statusCode: "403", rejectedReason: "当日调用配额已用完", durationMs: 40 });
    else push(i, "超时", { statusCode: "504", errorMasked: "gateway timeout (masked)", durationMs: 3000 });
  }
  return events;
}

/** 场景 K：某部门一小时内 50 次越权字段请求（2026-08-13 09:00-10:00）。 */
function buildViolationEvents(): AuditEvent[] {
  const events: AuditEvent[] = [];
  for (let i = 1; i <= 50; i += 1) {
    const minute = String((i - 1) % 60).padStart(2, "0");
    events.push({
      id: `ev-violate-${i}`,
      at: `2026-08-13 09:${minute}:00`,
      principal: "市场部-活动系统",
      principalKind: "部门",
      appId: "app-campaign",
      appNameMasked: "活动运营平台",
      channel: "API",
      ipRegion: "内网-市场区",
      accountMasked: "svc-camp***",
      traceId: `trc-violate-${i}`,
      productId: "p-customer-query-api",
      productName: "客户经营查询 API",
      serviceVersion: 1,
      assetId: "asset-customer-table",
      assetVersion: 2,
      authorizationId: "az-market-expired",
      authorizedPurpose: "营销推荐",
      declaredPurpose: "营销推荐",
      result: "拒绝",
      statusCode: "403",
      rejectedReason: "字段超出授权范围：mobile",
      durationMs: 35,
    });
  }
  return events;
}

export const defaultAuditEvents: AuditEvent[] = [
  ...buildGeneratedEvents(),
  ...buildViolationEvents(),
  {
    id: "ev-cust-128",
    at: "2026-08-13 08:30:00",
    principal: "风控部-风控系统",
    principalKind: "内部系统",
    appId: "app-risk-engine",
    appNameMasked: "风控决策引擎",
    channel: "API",
    ipRegion: "内网-风控区",
    accountMasked: "svc-risk***",
    traceId: "trc-128rec",
    productId: "p-customer-query-api",
    productName: "客户经营查询 API",
    serviceVersion: 1,
    assetId: "asset-customer-table",
    assetVersion: 2,
    authorizationId: "az-risk-system",
    authorizedPurpose: "贷款风险审核",
    declaredPurpose: "贷款风险审核",
    result: "成功",
    statusCode: "200",
    recordCount: 128,
    durationMs: 230,
  },
  {
    id: "ev-purpose-mismatch",
    at: "2026-08-13 08:45:00",
    principal: "市场部-活动系统",
    principalKind: "部门",
    appId: "app-campaign",
    appNameMasked: "活动运营平台",
    channel: "API",
    ipRegion: "内网-市场区",
    accountMasked: "svc-camp***",
    traceId: "trc-mismatch",
    productId: "p-customer-query-api",
    productName: "客户经营查询 API",
    serviceVersion: 1,
    assetId: "asset-customer-labels",
    assetVersion: 3,
    authorizationId: "az-risk-system",
    authorizedPurpose: "贷款风险审核",
    declaredPurpose: "营销推荐",
    result: "拒绝",
    statusCode: "403",
    rejectedReason: "目的不一致：声明「营销推荐」与授权目的「贷款风险审核」不符",
    durationMs: 30,
  },
  {
    id: "ev-field-mobile",
    at: "2026-08-13 08:50:00",
    principal: "风控部-风控系统",
    principalKind: "内部系统",
    appId: "app-risk-engine",
    appNameMasked: "风控决策引擎",
    channel: "API",
    ipRegion: "内网-风控区",
    accountMasked: "svc-risk***",
    traceId: "trc-field-mobile",
    productId: "p-customer-query-api",
    productName: "客户经营查询 API",
    serviceVersion: 1,
    assetId: "asset-customer-table",
    assetVersion: 2,
    authorizationId: "az-risk-system",
    authorizedPurpose: "贷款风险审核",
    declaredPurpose: "贷款风险审核",
    result: "拒绝",
    statusCode: "403",
    rejectedReason: "字段超出授权范围：mobile",
    durationMs: 32,
  },
  {
    id: "ev-settle-partner",
    at: "2026-08-13 09:05:00",
    principal: "合作机构A-结算系统",
    principalKind: "外部机构",
    appId: "app-partner-settle",
    appNameMasked: "合作结算系统",
    channel: "API",
    ipRegion: "外联网区域",
    accountMasked: "svc-settle***",
    traceId: "trc-settle",
    productId: "p-ec-region-api",
    productName: "华东区域经营 API",
    serviceVersion: 1,
    assetId: "asset-ec-region-data",
    assetVersion: 1,
    authorizationId: "az-partner-a-settle",
    authorizedPurpose: "外部合作结算",
    declaredPurpose: "外部合作结算",
    result: "拒绝",
    statusCode: "403",
    rejectedReason: "产品未处于已发布状态（已暂停）",
    durationMs: 28,
  },
  {
    id: "ev-download-ok",
    at: "2026-08-13 09:10:00",
    principal: "业务分析-李梅",
    principalKind: "人员",
    appId: "app-analyst",
    appNameMasked: "个人工作台",
    channel: "下载",
    ipRegion: "内网-分析区",
    accountMasked: "user-li***",
    traceId: "trc-dl-1",
    productId: "p-customer-ops-download",
    productName: "客户经营分析报告下载",
    serviceVersion: 1,
    assetId: "asset-customer-ops-report",
    assetVersion: 1,
    authorizationId: "az-analyst-download",
    authorizedPurpose: "经营分析",
    declaredPurpose: "经营分析",
    result: "成功",
    statusCode: "200",
    fileSizeKB: 1284,
    durationMs: 860,
  },
  {
    id: "ev-download-refused-3rd",
    at: "2026-08-13 09:12:00",
    principal: "业务分析-李梅",
    principalKind: "人员",
    appId: "app-analyst",
    appNameMasked: "个人工作台",
    channel: "下载",
    ipRegion: "内网-分析区",
    accountMasked: "user-li***",
    traceId: "trc-dl-3",
    productId: "p-customer-ops-download",
    productName: "客户经营分析报告下载",
    serviceVersion: 1,
    assetId: "asset-customer-ops-report",
    assetVersion: 1,
    authorizationId: "az-analyst-download",
    authorizedPurpose: "经营分析",
    declaredPurpose: "经营分析",
    result: "拒绝",
    statusCode: "403",
    rejectedReason: "已超过最大下载次数（48 小时内最多 2 次）",
    durationMs: 25,
  },
  {
    id: "ev-preview-report",
    at: "2026-08-13 09:15:00",
    principal: "业务分析-李梅",
    principalKind: "人员",
    appId: "app-analyst",
    appNameMasked: "个人工作台",
    channel: "预览",
    ipRegion: "内网-分析区",
    accountMasked: "user-li***",
    traceId: "trc-preview",
    productId: "p-customer-ops-download",
    productName: "客户经营分析报告下载",
    serviceVersion: 1,
    assetId: "asset-customer-ops-report",
    assetVersion: 1,
    authorizationId: "az-analyst-download",
    authorizedPurpose: "经营分析",
    declaredPurpose: "经营分析",
    result: "成功",
    statusCode: "200",
    recordCount: 12,
    durationMs: 310,
  },
  {
    id: "ev-query-online",
    at: "2026-08-13 09:20:00",
    principal: "经营分析组",
    principalKind: "部门",
    appId: "app-bi",
    appNameMasked: "BI 分析平台",
    channel: "在线查询",
    ipRegion: "内网-分析区",
    accountMasked: "user-an***",
    traceId: "trc-bi-1",
    productId: "p-customer-ops-download",
    productName: "客户经营分析报告下载",
    serviceVersion: 1,
    assetId: "asset-customer-ops-report",
    assetVersion: 1,
    authorizationId: "az-analyst-download",
    authorizedPurpose: "经营分析",
    declaredPurpose: "经营分析",
    result: "成功",
    statusCode: "200",
    recordCount: 96,
    durationMs: 420,
  },
];

export const defaultAnomalies: Anomaly[] = [
  {
    id: "an-field-violation",
    rule: "violation-fields",
    ruleLabel: "越权字段请求",
    severity: "高",
    eventIds: Array.from({ length: 50 }, (_, index) => `ev-violate-${index + 1}`),
    principal: "市场部-活动系统",
    productName: "客户经营查询 API",
    channel: "API",
    status: "整改中",
    createdAt: "2026-08-13 09:10:00",
    owner: "风控运营-王强",
    judgeBasis: "一小时内 50 次越权字段（mobile）请求，排除压测声明，确认为越权访问",
    judgedBy: "审计人员-钱审计",
    judgedAt: "2026-08-13 09:30:00",
    rectificationId: "rect-violation",
  },
  {
    id: "an-purpose-mismatch",
    rule: "purpose-mismatch",
    ruleLabel: "访问目的不一致",
    severity: "中",
    eventIds: ["ev-purpose-mismatch"],
    principal: "市场部-活动系统",
    productName: "客户经营查询 API",
    channel: "API",
    status: "待研判",
    createdAt: "2026-08-13 08:45:00",
  },
  {
    id: "an-download-frequency",
    rule: "download-frequency",
    ruleLabel: "异常下载频率",
    severity: "低",
    eventIds: ["ev-download-refused-3rd"],
    principal: "业务分析-李梅",
    productName: "客户经营分析报告下载",
    channel: "下载",
    status: "待研判",
    createdAt: "2026-08-13 09:12:00",
  },
  {
    id: "an-continuous-failure",
    rule: "continuous-failure",
    ruleLabel: "连续失败调用",
    severity: "中",
    eventIds: ["ev-p3-925", "ev-p3-926", "ev-p3-927"],
    principal: "风控部-旧查询系统",
    productName: "客户经营查询 API",
    channel: "API",
    status: "已关闭",
    createdAt: "2026-08-02 14:00:00",
    owner: "风控运营-王强",
    judgeBasis: "旧系统连续 5 小时失败率 > 60%，确认为异常",
    judgedBy: "审计人员-钱审计",
    judgedAt: "2026-08-02 15:00:00",
    rectificationId: "rect-continuous",
  },
  {
    id: "an-legal-pressure-test",
    rule: "load-test",
    ruleLabel: "疑似压测（已排除）",
    severity: "低",
    eventIds: ["ev-p3-500", "ev-p3-501"],
    principal: "性能测试组",
    productName: "客户经营查询 API",
    channel: "API",
    status: "已排除",
    createdAt: "2026-07-12 03:00:00",
    judgeBasis: "匹配压测计划书 T-2026-0712（2026-07-12 02:00-03:00），判定为合法压测",
    judgedBy: "审计人员-钱审计",
    judgedAt: "2026-07-12 04:00:00",
  },
  {
    id: "an-partner-downtime",
    rule: "product-paused",
    ruleLabel: "暂停产品访问",
    severity: "低",
    eventIds: ["ev-settle-partner"],
    principal: "合作机构A-结算系统",
    productName: "华东区域经营 API",
    channel: "API",
    status: "已确认异常",
    createdAt: "2026-09-01 00:05:00",
    owner: "运营人员-何运营",
    judgeBasis: "经营权到期后产品自动暂停，外部系统在暂停窗口内访问被拒，属预期行为",
    judgedBy: "审计人员-钱审计",
    judgedAt: "2026-09-01 09:00:00",
  },
];

export const defaultRectifications: Rectification[] = [
  {
    id: "rect-violation",
    anomalyId: "an-field-violation",
    owner: "风控运营-王强",
    measure: "撤销市场部越权授权并复核字段授权范围；同步回收活动系统 mobile 字段请求能力",
    dueAt: "2026-08-20",
    status: "整改中",
    createdAt: "2026-08-13 09:40:00",
  },
  {
    id: "rect-continuous",
    anomalyId: "an-continuous-failure",
    owner: "风控运营-王强",
    measure: "旧查询系统下线并迁移至新系统，撤销旧授权",
    dueAt: "2026-08-05",
    status: "已关闭",
    createdAt: "2026-08-02 15:30:00",
    reviewBasis: "旧系统已下线，连续失败率归零，风险消除",
    reviewedBy: "复核人-郑复核",
    reviewedAt: "2026-08-10 10:00:00",
  },
];
