/** Data Asset · mock 目录数据：资产、版本、扫描任务、变更记录。 */

import type { Asset, AssetField, AssetVersion, BusinessDomain, ChangeRecord, ScanLogLine, ScanTask } from "../types";

function tableExt(database: string, schema: string, table: string, fields: AssetField[], rowCount?: number) {
  return { database, schema, table, fields, rowCount };
}

export const defaultAssets: Asset[] = [
  {
    id: "asset-customer-labels",
    name: "客户标签库",
    type: "tag",
    sourceSystem: "CRM 客户中心",
    sourceObjectId: "obj-crm-taglib",
    businessDomain: "客户运营",
    description: "基于客户行为与画像生成的标签集合，支撑营销、风控与经营分析。",
    tags: ["客户", "标签", "画像"],
    owner: "张明",
    securityLevel: "L3-敏感",
    catalogStatus: "normal",
    version: 3,
    updatedAt: "2026-06-18 10:24:00",
    ext: { relatedDatasets: ["customer 客户信息表"], updateCycle: "每日" },
  },
  {
    id: "asset-customer-table",
    name: "customer 客户信息表",
    type: "table",
    sourceSystem: "CRM 客户中心",
    sourceObjectId: "obj-crm-customer",
    businessDomain: "客户运营",
    description: "客户主数据表，V2 起新增手机号敏感字段。",
    tags: ["客户", "主数据"],
    owner: "张明",
    securityLevel: "L3-敏感",
    catalogStatus: "normal",
    version: 2,
    updatedAt: "2026-07-21 02:15:00",
    ext: tableExt("crm", "public", "customer", [
      { name: "customer_id", type: "bigint", primaryKey: true, sensitive: false, comment: "客户 ID" },
      { name: "name", type: "varchar(64)", sensitive: false, comment: "客户名称" },
      { name: "mobile", type: "varchar(20)", sensitive: true, securityLevel: "L3-敏感", comment: "手机号（V2 新增）" },
      { name: "risk_level", type: "varchar(16)", sensitive: false, comment: "风险等级" },
      { name: "province", type: "varchar(32)", sensitive: false, comment: "所在省份" },
      { name: "created_at", type: "timestamp", sensitive: false, comment: "创建时间" },
    ], 860000),
  },
  {
    id: "asset-orders-2026",
    name: "orders_2026 订单表",
    type: "table",
    sourceSystem: "CRM 客户中心",
    sourceObjectId: "obj-crm-orders2026",
    businessDomain: "交易",
    description: "2026 年度订单明细表，夜间增量扫描新发现对象，待确权。",
    tags: ["订单", "交易"],
    owner: "张明",
    securityLevel: "L2-一般",
    catalogStatus: "normal",
    version: 1,
    updatedAt: "2026-08-12 02:03:00",
    ext: tableExt("crm", "public", "orders_2026", [
      { name: "order_id", type: "bigint", primaryKey: true, sensitive: false, comment: "订单 ID" },
      { name: "customer_id", type: "bigint", sensitive: false, comment: "客户 ID" },
      { name: "amount", type: "decimal(12,2)", sensitive: false, comment: "订单金额" },
      { name: "order_time", type: "timestamp", sensitive: false, comment: "下单时间" },
    ], 1250000),
  },
  {
    id: "asset-customer-profile",
    name: "customer_profile 客户画像表",
    type: "table",
    sourceSystem: "CRM 客户中心",
    sourceObjectId: "obj-crm-customer",
    businessDomain: "客户运营",
    description: "由 customer_info 重命名而来，来源对象 ID 不变，沿用资产 ID 并生成新版本。",
    tags: ["客户", "画像"],
    owner: "李华",
    securityLevel: "L3-敏感",
    catalogStatus: "normal",
    version: 2,
    updatedAt: "2026-07-30 11:40:00",
    ext: tableExt("crm", "public", "customer_profile", [
      { name: "customer_id", type: "bigint", primaryKey: true, sensitive: false, comment: "客户 ID" },
      { name: "profile_json", type: "jsonb", sensitive: false, comment: "画像标签" },
      { name: "updated_at", type: "timestamp", sensitive: false, comment: "更新时间" },
    ], 740000),
  },
  {
    id: "asset-risk-model",
    name: "企业风险评分模型",
    type: "model",
    sourceSystem: "风控模型平台",
    sourceObjectId: "obj-risk-model-001",
    businessDomain: "风控",
    description: "企业风险评分模型，v1.2 引入司法数据特征后重新发布。",
    tags: ["模型", "风控", "评分"],
    owner: "陈审核",
    securityLevel: "L2-一般",
    catalogStatus: "normal",
    version: 2,
    updatedAt: "2026-08-03 16:20:00",
    ext: {
      modelType: "分类模型",
      inputOutput: "输入企业特征与司法特征，输出 0-100 风险评分",
      trainingData: "企业基本信息表 + 司法风险报告（2020-2026）",
      framework: "XGBoost",
      modelVersion: "v1.2",
      effectMetrics: "AUC 0.87 / KS 0.41",
    },
  },
  {
    id: "asset-enterprise-info",
    name: "企业基本信息表",
    type: "table",
    sourceSystem: "CRM 客户中心",
    sourceObjectId: "obj-crm-enterprise",
    businessDomain: "客户运营",
    description: "企业客户基本信息，支撑企业风险画像产品。",
    tags: ["企业", "主数据"],
    owner: "张明",
    securityLevel: "L2-一般",
    catalogStatus: "normal",
    version: 1,
    updatedAt: "2026-03-02 09:12:00",
    ext: tableExt("crm", "public", "enterprise_info", [
      { name: "ent_id", type: "bigint", primaryKey: true, sensitive: false, comment: "企业 ID" },
      { name: "ent_name", type: "varchar(128)", sensitive: false, comment: "企业名称" },
      { name: "industry", type: "varchar(32)", sensitive: false, comment: "行业" },
      { name: "registered_capital", type: "decimal(14,2)", sensitive: false, comment: "注册资本" },
    ], 320000),
  },
  {
    id: "asset-judicial-report",
    name: "司法风险报告",
    type: "document",
    subtype: "报告",
    sourceSystem: "司法数据服务",
    sourceObjectId: "obj-legal-report",
    businessDomain: "风控",
    description: "企业涉诉与司法风险报告，按周更新，供企业风险画像使用。",
    tags: ["司法", "风险", "报告"],
    owner: "陈审核",
    securityLevel: "L3-敏感",
    catalogStatus: "normal",
    version: 1,
    updatedAt: "2026-08-10 08:30:00",
    ext: { reportFormat: "PDF", relatedDatasets: ["司法裁判文书库"], updateCycle: "周", generateSystem: "司法数据服务", reportVersion: "2026R3" },
  },
  {
    id: "asset-region-sales-report",
    name: "区域销售月报",
    type: "document",
    subtype: "报告",
    sourceSystem: "BI 报表平台",
    sourceObjectId: "obj-bi-region-sales",
    businessDomain: "经营分析",
    description: "按区域汇总的月度销售报告，V2 模板升级后更新周期保持月更。",
    tags: ["销售", "月报"],
    owner: "王芳",
    securityLevel: "L2-一般",
    catalogStatus: "normal",
    version: 2,
    updatedAt: "2026-08-05 18:10:00",
    ext: { reportFormat: "Excel", relatedDatasets: ["orders_2026 订单表"], updateCycle: "月", generateSystem: "BI 报表平台", reportVersion: "v2" },
  },
  {
    id: "asset-customer-ops-report",
    name: "客户经营分析报告",
    type: "document",
    subtype: "报告",
    sourceSystem: "BI 报表平台",
    sourceObjectId: "obj-bi-customer-ops",
    businessDomain: "经营分析",
    description: "客户经营分析报告，支持在线查询与下载交付。",
    tags: ["客户", "分析", "报告"],
    owner: "王芳",
    securityLevel: "L3-敏感",
    catalogStatus: "normal",
    version: 1,
    updatedAt: "2026-07-15 14:00:00",
    ext: { reportFormat: "PDF", relatedDatasets: ["customer 客户信息表"], updateCycle: "月", generateSystem: "BI 报表平台", reportVersion: "v1" },
  },
  {
    id: "asset-customer-info-old",
    name: "customer_info 旧表",
    type: "table",
    sourceSystem: "CRM 客户中心",
    sourceObjectId: "obj-crm-customer-info",
    businessDomain: "客户运营",
    description: "来源对象暂时无法扫描到，标记来源异常待确认，不自动删除。",
    tags: ["客户"],
    owner: "李华",
    securityLevel: "L2-一般",
    catalogStatus: "sourceAbnormal",
    version: 1,
    updatedAt: "2026-08-12 02:30:00",
    ext: tableExt("crm", "public", "customer_info", []),
  },
  {
    id: "asset-legacy-sales-table",
    name: "旧销售明细表",
    type: "table",
    sourceSystem: "BI 报表平台",
    sourceObjectId: "obj-bi-legacy-sales",
    businessDomain: "经营分析",
    description: "来源数据库已正式删除，仍关联下载产品与两条有效授权，处于待退役状态。",
    tags: ["销售", "历史"],
    owner: "王芳",
    securityLevel: "L2-一般",
    catalogStatus: "retiring",
    version: 1,
    updatedAt: "2026-08-11 09:00:00",
    ext: tableExt("bi", "ods", "sales_detail", [
      { name: "id", type: "bigint", primaryKey: true, sensitive: false, comment: "主键" },
      { name: "region", type: "varchar(32)", sensitive: false, comment: "区域" },
    ], 5000000),
  },
  {
    id: "asset-ec-region-data",
    name: "华东区域经营数据集",
    type: "dataset",
    sourceSystem: "BI 报表平台",
    sourceObjectId: "obj-bi-ec-region",
    businessDomain: "经营分析",
    description: "华东区域经营数据，合作机构 A 的新经营权于 2026-09-01 生效。",
    tags: ["华东", "合作"],
    owner: "王芳",
    securityLevel: "L2-一般",
    catalogStatus: "normal",
    version: 1,
    updatedAt: "2026-08-13 08:00:00",
    ext: { relatedDatasets: ["orders_2026 订单表"], updateCycle: "日" },
  },
];

export const defaultAssetVersions: AssetVersion[] = [
  { id: "av-customer-labels-v2", assetId: "asset-customer-labels", version: 2, changedAt: "2026-04-02 10:00:00", changedBy: "扫描器", reason: "标签字段结构调整", diff: ["新增字段：消费分层标签", "调整字段：活跃度等级口径"] },
  { id: "av-customer-labels-v3", assetId: "asset-customer-labels", version: 3, changedAt: "2026-06-18 10:24:00", changedBy: "扫描器", reason: "标签口径更新（营销分层）", diff: ["更新：分层口径由 4 级调整为 5 级"] },
  { id: "av-customer-table-v2", assetId: "asset-customer-table", version: 2, changedAt: "2026-07-21 02:15:00", changedBy: "扫描器", reason: "新增手机号敏感字段", diff: ["新增字段：mobile（L3-敏感）"] },
  { id: "av-customer-profile-v1", assetId: "asset-customer-profile", version: 1, changedAt: "2026-03-15 09:00:00", changedBy: "扫描器", reason: "初始编目（customer_info）", diff: ["初始版本"] },
  { id: "av-customer-profile-v2", assetId: "asset-customer-profile", version: 2, changedAt: "2026-07-30 11:40:00", changedBy: "扫描器", reason: "来源对象名称变化：customer_info → customer_profile", diff: ["表名变更", "字段结构调整"] },
  { id: "av-risk-model-v1", assetId: "asset-risk-model", version: 1, changedAt: "2026-06-15 10:00:00", changedBy: "扫描器", reason: "初始注册", diff: ["初始版本"] },
  { id: "av-risk-model-v2", assetId: "asset-risk-model", version: 2, changedAt: "2026-08-03 16:20:00", changedBy: "扫描器", reason: "模型升级 v1.1 → v1.2（新增司法特征）", diff: ["模型版本变更", "效果指标更新：AUC 0.85 → 0.87"] },
  { id: "av-region-sales-v2", assetId: "asset-region-sales-report", version: 2, changedAt: "2026-08-05 18:10:00", changedBy: "扫描器", reason: "报表模板升级", diff: ["新增列：目标达成率"] },
  { id: "av-legacy-sales-v1", assetId: "asset-legacy-sales-table", version: 1, changedAt: "2026-03-01 08:00:00", changedBy: "扫描器", reason: "初始编目", diff: ["初始版本"] },
  { id: "av-ec-region-v1", assetId: "asset-ec-region-data", version: 1, changedAt: "2026-08-13 08:00:00", changedBy: "扫描器", reason: "初始编目", diff: ["初始版本"] },
];

function logLine(time: string, level: ScanLogLine["level"], text: string): ScanLogLine {
  return { time, level, text };
}

export const defaultScanTasks: ScanTask[] = [
  {
    id: "scan-20260812-night",
    name: "CRM 夜间增量扫描",
    sourceSystem: "CRM 客户中心",
    mode: "incremental",
    range: "schema: crm.public",
    status: "partial",
    triggeredBy: "周期任务",
    startedAt: "2026-08-12 02:00:00",
    finishedAt: "2026-08-12 02:41:00",
    found: 200,
    added: 1,
    changed: 2,
    abnormal: 1,
    errorSummary: "10 个对象因来源 API 限流失败，可重试失败对象",
    logs: [
      logLine("2026-08-12 02:00:00", "INFO", "扫描启动：schema=crm.public, mode=incremental"),
      logLine("2026-08-12 02:03:00", "INFO", "新增对象：orders_2026（自动编目，待确权）"),
      logLine("2026-08-12 02:15:00", "INFO", "变更对象：customer（新增字段 mobile，生成 V2）"),
      logLine("2026-08-12 02:30:00", "WARN", "来源不可用：customer_info 未扫描到，标记来源异常"),
      logLine("2026-08-12 02:38:00", "ERROR", "10 个对象调用失败：source API rate limit (429)"),
      logLine("2026-08-12 02:41:00", "INFO", "任务结束：190 个对象成功，10 个失败"),
    ],
    failedObjects: [
      { id: "obj-crm-order-extra-1", name: "order_ext_202605", reason: "source API rate limit (429)", retried: false },
      { id: "obj-crm-order-extra-2", name: "order_ext_202606", reason: "source API rate limit (429)", retried: false },
    ],
  },
  {
    id: "scan-20260805-bi",
    name: "BI 报表平台扫描",
    sourceSystem: "BI 报表平台",
    mode: "incremental",
    range: "报表目录: 经营分析",
    status: "success",
    triggeredBy: "周期任务",
    startedAt: "2026-08-05 03:00:00",
    finishedAt: "2026-08-05 03:18:00",
    found: 8,
    added: 0,
    changed: 1,
    abnormal: 0,
    logs: [
      logLine("2026-08-05 03:00:00", "INFO", "扫描启动：报表目录=经营分析"),
      logLine("2026-08-05 03:16:00", "INFO", "变更对象：区域销售月报（模板升级，生成 V2）"),
      logLine("2026-08-05 03:18:00", "INFO", "任务完成，无异常"),
    ],
    failedObjects: [],
  },
  {
    id: "scan-20260803-risk",
    name: "风控模型平台扫描",
    sourceSystem: "风控模型平台",
    mode: "incremental",
    range: "模型注册库",
    status: "success",
    triggeredBy: "周期任务",
    startedAt: "2026-08-03 03:30:00",
    finishedAt: "2026-08-03 03:35:00",
    found: 3,
    added: 0,
    changed: 1,
    abnormal: 0,
    logs: [
      logLine("2026-08-03 03:30:00", "INFO", "扫描启动：模型注册库"),
      logLine("2026-08-03 03:33:00", "INFO", "变更对象：企业风险评分模型（v1.1 → v1.2）"),
      logLine("2026-08-03 03:35:00", "INFO", "任务完成，无异常"),
    ],
    failedObjects: [],
  },
  {
    id: "scan-20260813-crm-full",
    name: "CRM 全量扫描",
    sourceSystem: "CRM 客户中心",
    mode: "full",
    range: "全部库表",
    status: "pending",
    triggeredBy: "手动触发（排队中）",
    found: 0,
    added: 0,
    changed: 0,
    abnormal: 0,
    logs: [],
    failedObjects: [],
  },
];

export const defaultChanges: ChangeRecord[] = [
  {
    id: "chg-001",
    assetId: "asset-customer-labels",
    at: "2026-06-01 14:30:00",
    actor: "资产管理员-系统",
    kind: "负责人变更",
    before: "负责人：王芳",
    after: "负责人：张明",
    reason: "张明调岗至客户标签库负责人；数据中心仍为持有主体，不生成权属版本",
  },
  {
    id: "chg-002",
    assetId: "asset-customer-labels",
    at: "2026-05-20 09:00:00",
    actor: "张明",
    kind: "目录信息变更",
    before: "标签：客户、画像",
    after: "标签：客户、标签、画像",
    reason: "补充营销分层标签",
  },
  {
    id: "chg-003",
    assetId: "asset-legacy-sales-table",
    at: "2026-08-11 09:00:00",
    actor: "扫描器",
    kind: "来源删除确认",
    before: "状态：正常",
    after: "状态：待退役",
    reason: "来源数据库已正式删除，需先下线关联产品并处理授权",
  },
];

export const defaultDomains: BusinessDomain[] = [
  { id: "domain-customer", name: "客户运营", parentId: null, order: 1 },
  { id: "domain-customer-master", name: "客户主数据", parentId: "domain-customer", order: 1 },
  { id: "domain-customer-tag", name: "客户标签与画像", parentId: "domain-customer", order: 2 },
  { id: "domain-trade", name: "交易", parentId: null, order: 2 },
  { id: "domain-risk", name: "风控", parentId: null, order: 3 },
  { id: "domain-risk-model", name: "风险模型", parentId: "domain-risk", order: 1 },
  { id: "domain-risk-judicial", name: "司法风险", parentId: "domain-risk", order: 2 },
  { id: "domain-ops", name: "经营分析", parentId: null, order: 4 },
  { id: "domain-uncategorized", name: "未分类", parentId: null, order: 99 },
];
