/** Data Asset · 直接资产流通 mock：申请、审批、对接与使用证据。 */

import type {
  AssetCirculationApplication,
  AssetIntegrationTask,
  AssetUsageRecord,
} from "../types";

export const defaultCirculationApplications: AssetCirculationApplication[] = [
  {
    id: "circulation-standard-trade",
    title: "经营分析系统引用月度交易额口径",
    asset: {
      assetId: "asset-standard-monthly-trade",
      assetName: "月度交易额口径",
      assetType: "standard",
      assetVersion: 7,
      securityLevel: "内部",
      standardCode: "STD-METRIC-0007",
      standardVersion: "v7",
    },
    applicant: "刘洋",
    applicantOrg: "经营分析部",
    applicantKind: "内部",
    consumerSystem: "经营分析指标平台",
    purpose: "经营分析",
    purposeNote: "统一集团月度交易额看板口径",
    requestedScope: "标准定义、计算逻辑、过滤条件与维度说明",
    delivery: "标准引用",
    effectiveFrom: "2026-08-13",
    effectiveTo: "2027-08-12",
    status: "inUse",
    stage: "use",
    requiresSecurity: false,
    submittedAt: "2026-08-10 09:30:00",
    updatedAt: "2026-08-12 17:00:00",
    grantNo: "GRANT-STD-202608-001",
    integrationTaskId: "integration-standard-trade",
    approvals: [
      { id: "approval-standard-owner", role: "资产负责人", assignee: "张敏", status: "approved", opinion: "用途与适用范围一致，同意引用 v7。", processedBy: "张敏", processedAt: "2026-08-10 14:20:00" },
      { id: "approval-standard-security", role: "安全审批人", assignee: "安全管理员", status: "skipped", opinion: "内部标准引用，无需安全加签。" },
    ],
  },
  {
    id: "circulation-external-labels",
    title: "合作机构 A 申请客户标签 API",
    asset: {
      assetId: "asset-customer-labels",
      assetName: "客户标签库",
      assetType: "tag",
      assetVersion: 3,
      securityLevel: "L3-敏感",
    },
    applicant: "合作机构 A",
    applicantOrg: "合作机构 A",
    applicantKind: "外部",
    consumerSystem: "合作营销平台（脱敏）",
    purpose: "活动运营分析",
    purposeNote: "仅用于华东区域活动效果分析",
    requestedScope: "客户分层、活跃度等级；不含直接标识字段",
    delivery: "API",
    effectiveFrom: "2026-08-15",
    effectiveTo: "2026-11-15",
    status: "pendingSecurity",
    stage: "approval",
    requiresSecurity: true,
    submittedAt: "2026-08-12 10:10:00",
    updatedAt: "2026-08-13 08:30:00",
    approvals: [
      { id: "approval-label-owner", role: "资产负责人", assignee: "张明", status: "approved", opinion: "业务用途明确，范围已收窄。", processedBy: "张明", processedAt: "2026-08-12 16:40:00" },
      { id: "approval-label-security", role: "安全审批人", assignee: "林安全", status: "pending" },
    ],
  },
  {
    id: "circulation-risk-model",
    title: "贷后系统申请企业风险评分模型",
    asset: {
      assetId: "asset-risk-model",
      assetName: "企业风险评分模型",
      assetType: "model",
      assetVersion: 2,
      securityLevel: "L3-敏感",
    },
    applicant: "赵宁",
    applicantOrg: "风险管理部",
    applicantKind: "内部",
    consumerSystem: "贷后风险预警系统",
    purpose: "贷款风险审核",
    purposeNote: "批量评估存量企业客户风险",
    requestedScope: "模型评分与风险等级，不返回训练特征明细",
    delivery: "API",
    effectiveFrom: "2026-08-15",
    effectiveTo: "2027-02-15",
    status: "pendingOwner",
    stage: "approval",
    requiresSecurity: true,
    submittedAt: "2026-08-13 08:15:00",
    updatedAt: "2026-08-13 08:15:00",
    approvals: [
      { id: "approval-risk-owner", role: "资产负责人", assignee: "赵强", status: "pending" },
      { id: "approval-risk-security", role: "安全审批人", assignee: "林安全", status: "pending" },
    ],
  },
  {
    id: "circulation-report-download",
    title: "市场部申请客户经营分析报告",
    asset: {
      assetId: "asset-customer-ops-report",
      assetName: "客户经营分析报告",
      assetType: "document",
      assetVersion: 1,
      securityLevel: "L3-敏感",
    },
    applicant: "王珊",
    applicantOrg: "市场部",
    applicantKind: "内部",
    consumerSystem: "市场活动复盘工作台",
    purpose: "活动运营分析",
    purposeNote: "复盘 2026 年夏季活动",
    requestedScope: "华东区域、客户分群汇总数据",
    delivery: "文件下载",
    effectiveFrom: "2026-08-12",
    effectiveTo: "2026-08-31",
    status: "integrationFailed",
    stage: "integration",
    requiresSecurity: true,
    submittedAt: "2026-08-09 11:00:00",
    updatedAt: "2026-08-13 08:00:00",
    grantNo: "GRANT-DOC-202608-004",
    integrationTaskId: "integration-report-download",
    approvals: [
      { id: "approval-report-owner", role: "资产负责人", assignee: "王芳", status: "approved", opinion: "仅允许汇总数据。", processedBy: "王芳", processedAt: "2026-08-09 15:00:00" },
      { id: "approval-report-security", role: "安全审批人", assignee: "林安全", status: "approved", opinion: "必须应用手机号掩码并限制两次下载。", processedBy: "林安全", processedAt: "2026-08-10 10:20:00" },
    ],
  },
];

export const defaultIntegrationTasks: AssetIntegrationTask[] = [
  {
    id: "integration-standard-trade",
    applicationId: "circulation-standard-trade",
    assetId: "asset-standard-monthly-trade",
    delivery: "标准引用",
    owner: "平台对接-李浩",
    dueAt: "2026-08-13",
    status: "completed",
    configSummary: "data-agent:standard:STD-METRIC-0007@v7",
    checklist: [
      { id: "std-id", label: "企业指标 ID 已映射", status: "passed" },
      { id: "std-version", label: "标准版本已冻结为 v7", status: "passed" },
      { id: "std-lineage", label: "消费系统引用关系已登记", status: "passed" },
    ],
    lastResult: "标准引用校验通过，消费系统已绑定 v7。",
    completedAt: "2026-08-12 17:00:00",
    updatedAt: "2026-08-12 17:00:00",
  },
  {
    id: "integration-report-download",
    applicationId: "circulation-report-download",
    assetId: "asset-customer-ops-report",
    delivery: "文件下载",
    owner: "平台对接-周启",
    dueAt: "2026-08-14",
    status: "failed",
    configSummary: "PDF · 华东汇总 · 手机号掩码 · 48 小时 / 2 次",
    checklist: [
      { id: "doc-range", label: "数据范围与审批一致", status: "passed" },
      { id: "doc-mask", label: "脱敏策略校验", status: "failed", note: "手机号掩码规则未同步" },
      { id: "doc-download", label: "限时限次下载校验", status: "pending" },
    ],
    lastResult: "联调失败：手机号掩码规则未同步到 mock 交付配置。",
    updatedAt: "2026-08-13 08:00:00",
  },
];

export const defaultUsageRecords: AssetUsageRecord[] = [
  {
    id: "usage-standard-trade-001",
    applicationId: "circulation-standard-trade",
    assetId: "asset-standard-monthly-trade",
    assetName: "月度交易额口径",
    assetVersion: 7,
    consumerSystem: "经营分析指标平台",
    purpose: "经营分析",
    delivery: "标准引用",
    at: "2026-08-13 08:20:00",
    result: "成功",
    action: "解析并引用标准定义",
    volume: "1 次引用校验",
    evidenceNo: "EVD-CIRC-20260813-001",
  },
];
