/** Data Asset · mock 权属数据：权属关系、权属版本、变更审批。 */

import type { OwnershipApproval, OwnershipRight, OwnershipVersion } from "../types";

export const defaultRights: OwnershipRight[] = [
  {
    id: "right-customer-labels-hold",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    holder: "数据中心",
    holderKind: "内部部门",
    rightType: "持有权",
    dataScope: "全量数据",
    purpose: "持有与管理",
    effectiveFrom: "2026-01-01",
    effectiveTo: "2027-12-31",
    status: "confirmed",
    basis: "《客户标签库数据持有确认单》2026-001",
    version: 3,
    registeredBy: "权属登记员-赵敏",
    confirmedBy: "数据中心-王芳",
    createdAt: "2026-01-05 10:00:00",
    updatedAt: "2026-06-30 15:20:00",
  },
  {
    id: "right-customer-labels-use-market",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    holder: "市场部",
    holderKind: "内部部门",
    rightType: "使用权",
    dataScope: "营销相关标签字段",
    purpose: "营销活动运营",
    effectiveFrom: "2026-03-01",
    effectiveTo: "2026-12-31",
    status: "confirmed",
    basis: "《客户标签库使用权登记表》2026-014",
    version: 1,
    registeredBy: "权属登记员-赵敏",
    confirmedBy: "数据中心-王芳",
    createdAt: "2026-03-02 09:30:00",
    updatedAt: "2026-03-02 11:00:00",
  },
  {
    id: "right-customer-labels-use-risk",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    holder: "风控部",
    holderKind: "内部部门",
    rightType: "使用权",
    dataScope: "风险相关标签字段",
    purpose: "客户风险分析",
    effectiveFrom: "2026-03-01",
    effectiveTo: "2026-12-31",
    status: "confirmed",
    basis: "《客户标签库使用权登记表》2026-015",
    version: 1,
    registeredBy: "权属登记员-赵敏",
    confirmedBy: "数据中心-王芳",
    createdAt: "2026-03-02 09:40:00",
    updatedAt: "2026-03-02 11:05:00",
  },
  {
    id: "right-customer-labels-operate",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    holder: "数据运营部",
    holderKind: "内部部门",
    rightType: "经营权",
    dataScope: "内部使用全量数据",
    purpose: "内部数据产品运营",
    effectiveFrom: "2026-01-01",
    effectiveTo: "2027-06-30",
    status: "confirmed",
    basis: "《客户标签库经营权授权书》2026-003",
    version: 1,
    registeredBy: "权属登记员-赵敏",
    confirmedBy: "数据中心-王芳",
    createdAt: "2026-01-08 14:00:00",
    updatedAt: "2026-01-08 16:00:00",
  },
  {
    id: "right-customer-labels-partner-ec",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    holder: "合作机构A",
    holderKind: "外部机构",
    rightType: "经营权",
    dataScope: "华东区域经营数据",
    purpose: "区域联合经营",
    effectiveFrom: "2025-09-01",
    effectiveTo: "2026-08-31",
    status: "confirmed",
    basis: "《华东区域联合经营协议》2025-088",
    version: 2,
    registeredBy: "权属登记员-赵敏",
    confirmedBy: "数据中心-王芳",
    createdAt: "2025-08-20 10:00:00",
    updatedAt: "2026-05-10 09:30:00",
  },
  {
    id: "right-customer-table-hold",
    assetId: "asset-customer-table",
    assetName: "customer 客户信息表",
    holder: "数据中心",
    holderKind: "内部部门",
    rightType: "持有权",
    dataScope: "全量数据",
    purpose: "持有与管理",
    effectiveFrom: "2026-01-01",
    effectiveTo: "2027-12-31",
    status: "confirmed",
    basis: "《客户主数据持有确认单》2026-002",
    version: 1,
    registeredBy: "权属登记员-赵敏",
    confirmedBy: "数据中心-王芳",
    createdAt: "2026-01-06 10:00:00",
    updatedAt: "2026-01-06 12:00:00",
  },
  {
    id: "right-region-sales-hold",
    assetId: "asset-region-sales-report",
    assetName: "区域销售月报",
    holder: "市场部",
    holderKind: "内部部门",
    rightType: "持有权",
    dataScope: "全量数据",
    purpose: "持有与管理",
    effectiveFrom: "2026-02-01",
    effectiveTo: "2027-01-31",
    status: "confirmed",
    basis: "《区域销售月报持有确认单》2026-009",
    version: 1,
    registeredBy: "权属登记员-赵敏",
    confirmedBy: "市场部-李梅",
    createdAt: "2026-02-03 10:00:00",
    updatedAt: "2026-02-03 14:00:00",
  },
  {
    id: "right-ec-region-operate-new",
    assetId: "asset-ec-region-data",
    assetName: "华东区域经营数据集",
    holder: "合作机构A",
    holderKind: "外部机构",
    rightType: "经营权",
    dataScope: "华东区域经营数据",
    purpose: "区域联合经营（续期）",
    effectiveFrom: "2026-09-01",
    effectiveTo: "2027-08-31",
    status: "confirmed",
    basis: "《华东区域联合经营协议（续）》2026-102",
    version: 1,
    registeredBy: "权属登记员-赵敏",
    confirmedBy: "数据中心-王芳",
    createdAt: "2026-08-13 08:30:00",
    updatedAt: "2026-08-13 09:00:00",
  },
  {
    id: "right-orders-2026-pending",
    assetId: "asset-orders-2026",
    assetName: "orders_2026 订单表",
    holder: "数据运营部",
    holderKind: "内部部门",
    rightType: "持有权",
    dataScope: "全量数据",
    purpose: "持有与管理",
    effectiveFrom: "2026-08-12",
    effectiveTo: "2027-08-11",
    status: "pending",
    basis: "《订单表持有确认单》2026-120",
    version: 1,
    registeredBy: "权属登记员-赵敏",
    createdAt: "2026-08-12 03:00:00",
    updatedAt: "2026-08-12 03:00:00",
  },
];

export const defaultOwnershipVersions: OwnershipVersion[] = [
  {
    id: "ov-partner-ec-v1",
    rightId: "right-customer-labels-partner-ec",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    version: 1,
    changedAt: "2025-08-20 10:00:00",
    changedBy: "权属登记员-赵敏",
    reason: "初始登记：合作机构A 华东区域经营权",
    before: {},
    after: { holder: "合作机构A", rightType: "经营权", dataScope: "华东+华南区域", effectiveTo: "2026-08-31" },
    status: "已生效",
    approvedBy: "数据中心-王芳",
  },
  {
    id: "ov-partner-ec-v2",
    rightId: "right-customer-labels-partner-ec",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    version: 2,
    changedAt: "2026-05-10 09:30:00",
    changedBy: "权属登记员-赵敏",
    reason: "数据范围调整：华南区域合作终止，仅保留华东",
    before: { dataScope: "华东+华南区域", purpose: "区域联合经营" },
    after: { dataScope: "华东区域经营数据", purpose: "区域联合经营" },
    status: "已生效",
    approvedBy: "数据中心-王芳",
  },
  {
    id: "ov-hold-v2",
    rightId: "right-customer-labels-hold",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    version: 2,
    changedAt: "2026-06-30 15:20:00",
    changedBy: "权属登记员-赵敏",
    reason: "持有主体名称变更：大数据中心 → 数据中心",
    before: { holder: "大数据中心" },
    after: { holder: "数据中心" },
    status: "已生效",
    approvedBy: "数据中心-王芳",
  },
];

export const defaultOwnershipApprovals: OwnershipApproval[] = [
  {
    id: "oa-hold-v3",
    rightId: "right-customer-labels-hold",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    applicant: "权属登记员-赵敏",
    applicantKind: "变更",
    rightType: "持有权",
    holder: "数据中心",
    status: "已通过",
    submittedAt: "2026-06-28 10:00:00",
    processedBy: "数据中心-王芳",
    processedAt: "2026-06-30 15:20:00",
    opinion: "主体名称变更确认无误",
  },
  {
    id: "oa-partner-ec-v2",
    rightId: "right-customer-labels-partner-ec",
    assetId: "asset-customer-labels",
    assetName: "客户标签库",
    applicant: "权属登记员-赵敏",
    applicantKind: "变更",
    rightType: "经营权",
    holder: "合作机构A",
    status: "已通过",
    submittedAt: "2026-05-09 16:00:00",
    processedBy: "数据中心-王芳",
    processedAt: "2026-05-10 09:30:00",
    opinion: "华南合作终止，同意范围调整",
  },
  {
    id: "oa-orders-pending",
    rightId: "right-orders-2026-pending",
    assetId: "asset-orders-2026",
    assetName: "orders_2026 订单表",
    applicant: "权属登记员-赵敏",
    applicantKind: "登记",
    rightType: "持有权",
    holder: "数据运营部",
    status: "待确认",
    submittedAt: "2026-08-12 03:00:00",
  },
];
