/** Data Asset · mock 量化报告数据：八项指标与月度/季度管理报告。 */

import type { IndicatorResult, ManagementReport } from "../types";

const TRACE_CATALOG = ["扫描批次 scan-20260812-night", "资产版本 asset-customer-table#v2"];
const TRACE_OWNERSHIP = ["权属版本 ov-partner-ec-v2", "审批单 oa-partner-ec-v2"];
const TRACE_VALUATION = ["评估记录 ev-customer-labels-valid", "复核记录 rev-001"];
const TRACE_AUDIT = ["访问审计 2026-08-12 批次", "整改记录 rect-violation"];

export const defaultIndicators: IndicatorResult[] = [
  {
    id: "ind-catalog-complete",
    name: "目录编目完整率",
    definition: "已编目且必填信息完整的资产数 / 应编目资产数",
    calcFormula: "已编目且必填信息完整的资产数 ÷ 应编目资产数 × 100%",
    direction: "≥",
    target: 98,
    actual: 98.4,
    period: "2026-07",
    trend: "up",
    dataTime: "2026-08-01 08:00:00",
    traceableTo: TRACE_CATALOG,
  },
  {
    id: "ind-metadata-accuracy",
    name: "元数据准确率",
    definition: "抽检或校验通过的元数据项 / 已检查元数据项",
    calcFormula: "抽检通过的元数据项 ÷ 已检查元数据项 × 100%",
    direction: "≥",
    target: 97,
    actual: 97.6,
    period: "2026-07",
    trend: "flat",
    dataTime: "2026-08-01 08:00:00",
    traceableTo: TRACE_CATALOG,
  },
  {
    id: "ind-scan-timeliness",
    name: "扫描更新及时率",
    definition: "在规定时间内完成同步更新的变更数 / 已发现变更数",
    calcFormula: "按时完成的变更数 ÷ 已发现变更数 × 100%",
    direction: "≥",
    target: 95,
    actual: 92,
    period: "2026-07",
    trend: "down",
    dataTime: "2026-08-01 08:00:00",
    abnormalReason: "BI 报表平台扫描周期过长，8 项报表变更中 2 项超出 24 小时同步时限",
    improvement: "缩短报告系统扫描周期为每日两次，并配置同步超时告警",
    improvementDueAt: "2026-08-20",
    improvementStatus: "进行中",
    traceableTo: ["扫描批次 scan-20260805-bi", "扫描批次 scan-20260812-night"],
  },
  {
    id: "ind-ownership-complete",
    name: "权属登记完整率",
    definition: "权属必填信息完整的已登记资产数 / 应登记资产数",
    calcFormula: "权属必填完整的已登记资产数 ÷ 应登记资产数 × 100%",
    direction: "≥",
    target: 98,
    actual: 98.1,
    period: "2026-07",
    trend: "up",
    dataTime: "2026-08-01 08:00:00",
    traceableTo: TRACE_OWNERSHIP,
  },
  {
    id: "ind-ownership-change-timely",
    name: "权属变更按期完成率",
    definition: "在规定时限内完成的权属变更数 / 到期权属变更数",
    calcFormula: "时限内完成的权属变更数 ÷ 到期权属变更数 × 100%",
    direction: "≥",
    target: 95,
    actual: 96,
    period: "2026-07",
    trend: "up",
    dataTime: "2026-08-01 08:00:00",
    traceableTo: TRACE_OWNERSHIP,
  },
  {
    id: "ind-valuation-review-timely",
    name: "价值评估按期复核率",
    definition: "在规定时限内完成复核的评估数 / 到期应复核评估数",
    calcFormula: "时限内完成复核的评估数 ÷ 到期应复核评估数 × 100%",
    direction: "≥",
    target: 95,
    actual: 94.2,
    period: "2026-07",
    trend: "down",
    dataTime: "2026-08-01 08:00:00",
    abnormalReason: "复核人休假期间 1 份评估超过 3 个工作日复核时限",
    improvement: "为评估复核节点配置备选复核人并设置超时提醒",
    improvementDueAt: "2026-08-25",
    improvementStatus: "未开始",
    traceableTo: TRACE_VALUATION,
  },
  {
    id: "ind-audit-coverage",
    name: "运营访问审计覆盖率",
    definition: "已生成审计记录的数据访问数 / 全部数据访问数",
    calcFormula: "已生成审计记录的数据访问数 ÷ 全部数据访问数 × 100%",
    direction: "=",
    target: 100,
    actual: 100,
    period: "2026-07",
    trend: "flat",
    dataTime: "2026-08-01 08:00:00",
    traceableTo: TRACE_AUDIT,
  },
  {
    id: "ind-anomaly-closure",
    name: "异常访问闭环率",
    definition: "已完成整改并关闭的异常访问数 / 到期异常访问数",
    calcFormula: "已整改关闭的异常访问数 ÷ 到期异常访问数 × 100%",
    direction: "≥",
    target: 95,
    actual: 93.5,
    period: "2026-07",
    trend: "down",
    dataTime: "2026-08-01 08:00:00",
    abnormalReason: "1 条越权字段异常整改超期未复核关闭",
    improvement: "整改到期前 3 天自动提醒责任人并抄送审计人员",
    improvementDueAt: "2026-08-30",
    improvementStatus: "进行中",
    traceableTo: ["异常 an-continuous-failure", "整改记录 rect-violation"],
  },
];

export const defaultReports: ManagementReport[] = [
  {
    id: "rep-2026-07-catalog",
    kind: "目录质量",
    period: "2026-07",
    version: 1,
    frozen: true,
    generatedAt: "2026-08-01 08:30:00",
    generatedBy: "量化报告服务",
    indicators: defaultIndicators.slice(0, 3),
    summary: "目录编目完整率与元数据准确率达标；扫描更新及时率 92% 低于目标 95%，需缩短报告系统扫描周期。",
    gapReasons: [{ indicator: "扫描更新及时率", reason: "BI 报表平台扫描周期过长，2 项变更超出 24 小时同步时限" }],
    responsible: "资产管理员",
    measures: ["缩短报告系统扫描周期为每日两次", "配置同步超时告警"],
    dueAt: "2026-08-20",
    status: "未达标",
    reviewResult: "改进措施可行，按计划跟踪",
    reviewedBy: "数据管理委员会",
    reviewedAt: "2026-08-05 10:00:00",
  },
  {
    id: "rep-2026-07-ownership",
    kind: "权属管理",
    period: "2026-07",
    version: 1,
    frozen: true,
    generatedAt: "2026-08-01 08:30:00",
    generatedBy: "量化报告服务",
    indicators: defaultIndicators.slice(3, 5),
    summary: "权属登记完整率与变更按期完成率均达标；华东区域经营权 8 月 31 日到期提醒已按 30/7/1 天规则触达。",
    gapReasons: [],
    responsible: "权属登记员",
    measures: [],
    dueAt: "2026-08-31",
    status: "达标",
    reviewResult: "通过",
    reviewedBy: "数据管理委员会",
    reviewedAt: "2026-08-05 10:00:00",
  },
  {
    id: "rep-2026-07-valuation",
    kind: "价值评估",
    period: "2026-07",
    version: 1,
    frozen: true,
    generatedAt: "2026-08-01 08:30:00",
    generatedBy: "量化报告服务",
    indicators: defaultIndicators.slice(5, 6),
    summary: "价值评估按期复核率 94.2% 略低于目标；8 月客户标签库收益预测下调触发重评，原估值转为待替代。",
    gapReasons: [{ indicator: "价值评估按期复核率", reason: "复核人休假期间 1 份评估超过 3 个工作日复核时限" }],
    responsible: "评估复核人",
    measures: ["配置备选复核人", "复核超时提醒"],
    dueAt: "2026-08-25",
    status: "部分达标",
    reviewResult: "待确认备选复核人名单",
    reviewedBy: "数据管理委员会",
    reviewedAt: "2026-08-05 10:00:00",
  },
  {
    id: "rep-2026-07-service",
    kind: "资产运营",
    period: "2026-07",
    version: 1,
    frozen: true,
    generatedAt: "2026-08-01 08:30:00",
    generatedBy: "量化报告服务",
    indicators: defaultIndicators.slice(6, 7),
    summary: "运营访问审计覆盖率 100% 达标；发布门槛校验与授权审批流程运行正常。",
    gapReasons: [],
    responsible: "运营人员",
    measures: [],
    dueAt: "2026-08-31",
    status: "达标",
    reviewResult: "通过",
    reviewedBy: "数据管理委员会",
    reviewedAt: "2026-08-05 10:00:00",
  },
  {
    id: "rep-2026-07-audit",
    kind: "使用审计",
    period: "2026-07",
    version: 1,
    frozen: true,
    generatedAt: "2026-08-01 08:30:00",
    generatedBy: "量化报告服务",
    indicators: defaultIndicators.slice(7, 8),
    summary: "异常访问闭环率 93.5% 低于目标，1 条越权字段异常整改超期未复核关闭。",
    gapReasons: [{ indicator: "异常访问闭环率", reason: "越权字段异常整改超期未复核" }],
    responsible: "审计人员",
    measures: ["整改到期前 3 天自动提醒责任人", "抄送审计人员"],
    dueAt: "2026-08-30",
    status: "部分达标",
    reviewResult: "跟踪整改",
    reviewedBy: "数据管理委员会",
    reviewedAt: "2026-08-05 10:00:00",
  },
  {
    id: "rep-2026-q2-comprehensive",
    kind: "综合管理",
    period: "2026-Q2",
    version: 1,
    frozen: true,
    generatedAt: "2026-07-05 09:00:00",
    generatedBy: "量化报告服务",
    indicators: defaultIndicators,
    summary: "二季度整体达标率 75%（6/8 项达标）；扫描更新及时率与异常访问闭环率为主要差距项，已纳入三季度改进计划。",
    gapReasons: [
      { indicator: "扫描更新及时率", reason: "报告系统扫描周期过长" },
      { indicator: "异常访问闭环率", reason: "整改复核时效不足" },
    ],
    responsible: "数据管理委员会",
    measures: ["统一改进扫描周期与告警", "整改闭环时效专项治理"],
    dueAt: "2026-09-30",
    status: "部分达标",
    reviewResult: "通过，按季度跟踪",
    reviewedBy: "数据管理委员会",
    reviewedAt: "2026-07-08 10:00:00",
  },
  {
    id: "rep-2026-06-catalog",
    kind: "目录质量",
    period: "2026-06",
    version: 2,
    frozen: true,
    generatedAt: "2026-07-02 09:00:00",
    generatedBy: "量化报告服务",
    reviseReason: "6 月扫描及时率数据源修正，重新生成新版本，不覆盖历史报告",
    indicators: defaultIndicators.slice(0, 3),
    summary: "6 月目录质量达标；数据修正后及时率由 90% 修正为 91.2%。",
    gapReasons: [{ indicator: "扫描更新及时率", reason: "报告系统扫描周期过长（数据修正后重算）" }],
    responsible: "资产管理员",
    measures: ["缩短报告系统扫描周期"],
    dueAt: "2026-08-20",
    status: "未达标",
  },
];
