/** Data Asset · mock 资产运营数据：数据产品、发布审批、使用授权、下载任务、保留策略。 */

import type { Authorization, DataProduct, DownloadTask, ProductApproval, RetentionPolicy } from "../types";

export const defaultProducts: DataProduct[] = [
  {
    id: "p-region-sales-download",
    name: "区域销售月报下载",
    delivery: "下载",
    serviceVersion: 2,
    description: "按区域汇总的月度销售 Excel 报表，面向经营分析人员。",
    targetUsers: "经营分析人员",
    assets: [
      { assetId: "asset-region-sales-report", assetVersion: 2, usageScope: "全量报表内容", rightId: "right-region-sales-hold", purpose: "报表交付" },
    ],
    status: "草稿",
    gate: {
      checkedAt: "2026-08-13 09:00:00",
      passed: false,
      checks: [
        { name: "关联资产已确权", ok: true, detail: "全部关联资产权属已确权" },
        { name: "有效经营权覆盖数据范围与交付方式", ok: false, detail: "缺少有效经营权：asset-region-sales-report" },
        { name: "关联资产存在有效估值", ok: false, detail: "估值缺失或已失效：asset-region-sales-report" },
        { name: "产品服务版本信息完整", ok: true, detail: "服务版本信息完整" },
        { name: "发布审批与安全审核通过", ok: false, detail: "发布审批未完成或未通过" },
      ],
    },
    downloadConfig: { fileFormat: "Excel", updateCycle: "月", maxDownloads: 10, validHours: 48, masking: "金额列脱敏", dataRange: "全国" },
    operator: "运营人员-何运营",
    owner: "王芳",
    createdAt: "2026-08-01 10:00:00",
    updatedAt: "2026-08-13 09:00:00",
  },
  {
    id: "p-risk-profile-api",
    name: "企业风险画像 API",
    delivery: "API",
    serviceVersion: 2,
    description: "基于企业基本信息、司法风险报告与风险评分模型的风险画像查询 API。",
    targetUsers: "风控系统、合作机构",
    assets: [
      { assetId: "asset-enterprise-info", assetVersion: 1, usageScope: "企业基本信息字段", rightId: "right-customer-table-hold", purpose: "画像基础数据" },
      { assetId: "asset-judicial-report", assetVersion: 1, usageScope: "涉诉摘要", rightId: "right-customer-table-hold", purpose: "司法风险特征" },
      { assetId: "asset-risk-model", assetVersion: 2, usageScope: "评分结果", rightId: "right-customer-table-hold", purpose: "评分输出" },
    ],
    status: "已发布",
    apiConfig: { path: "/v2/enterprise/risk-profile", method: "POST", quotaPerDay: 5000, fields: ["ent_id", "ent_name", "risk_score", "risk_level"], region: "全国" },
    operator: "运营人员-何运营",
    owner: "陈审核",
    createdAt: "2026-06-10 09:00:00",
    updatedAt: "2026-08-04 10:00:00",
  },
  {
    id: "p-customer-query-api",
    name: "客户经营查询 API",
    delivery: "API",
    serviceVersion: 1,
    description: "客户经营信息查询 API，包含客户标签与客户主数据（含敏感字段管控）。",
    targetUsers: "风控、市场、合作机构",
    assets: [
      { assetId: "asset-customer-table", assetVersion: 2, usageScope: "客户主数据", rightId: "right-customer-table-hold", purpose: "查询服务" },
      { assetId: "asset-customer-labels", assetVersion: 3, usageScope: "标签数据", rightId: "right-customer-labels-operate", purpose: "标签查询" },
    ],
    status: "已发布",
    apiConfig: { path: "/v1/customer/query", method: "POST", quotaPerDay: 100000, fields: ["customer_id", "name", "risk_level", "province", "mobile"], region: "全国" },
    operator: "运营人员-何运营",
    owner: "张明",
    securityAlert: { reason: "关联资产 customer 客户信息表 V2 新增敏感字段 mobile，含该字段的下载/API 产品进入安全待复核", dueAt: "2026-08-31", state: "待复核" },
    createdAt: "2026-06-20 10:00:00",
    updatedAt: "2026-07-21 09:00:00",
  },
  {
    id: "p-customer-ops-download",
    name: "客户经营分析报告下载",
    delivery: "下载",
    serviceVersion: 1,
    description: "客户经营分析 PDF 报告下载服务。",
    targetUsers: "业务分析人员",
    assets: [
      { assetId: "asset-customer-ops-report", assetVersion: 1, usageScope: "报告全文", rightId: "right-region-sales-hold", purpose: "报告交付" },
    ],
    status: "已发布",
    downloadConfig: { fileFormat: "PDF", updateCycle: "月", maxDownloads: 5, validHours: 48, masking: "无", dataRange: "全国" },
    operator: "运营人员-何运营",
    owner: "王芳",
    createdAt: "2026-07-20 09:00:00",
    updatedAt: "2026-07-22 14:00:00",
  },
  {
    id: "p-ec-region-api",
    name: "华东区域经营 API",
    delivery: "API",
    serviceVersion: 1,
    description: "华东区域经营数据查询 API（合作机构 A 专属）。",
    targetUsers: "合作机构A 结算系统",
    assets: [
      { assetId: "asset-ec-region-data", assetVersion: 1, usageScope: "华东区域经营数据", rightId: "right-customer-labels-partner-ec", purpose: "区域联合经营" },
    ],
    status: "已暂停",
    statusReason: "经营权到期（2026-08-31）未续期，涉及华东区域的 API 已暂停；新权属 2026-09-01 生效后需运营核对并手动恢复",
    apiConfig: { path: "/v1/ec-region/query", method: "POST", quotaPerDay: 2000, fields: ["region", "amount", "order_count"], region: "华东" },
    operator: "运营人员-何运营",
    owner: "王芳",
    createdAt: "2025-09-10 09:00:00",
    updatedAt: "2026-08-31 23:59:00",
  },
  {
    id: "p-customer-labels-api",
    name: "客户标签 API",
    delivery: "API",
    serviceVersion: 1,
    description: "客户标签查询 API，当前关联资产估值处于待替代预警。",
    targetUsers: "内部系统",
    assets: [
      { assetId: "asset-customer-labels", assetVersion: 3, usageScope: "标签数据", rightId: "right-customer-labels-operate", purpose: "标签查询" },
    ],
    status: "已发布",
    apiConfig: { path: "/v1/customer-labels", method: "POST", quotaPerDay: 50000, fields: ["customer_id", "label_name", "label_value"], region: "全国" },
    operator: "运营人员-何运营",
    owner: "张明",
    createdAt: "2026-04-15 09:00:00",
    updatedAt: "2026-08-12 17:00:00",
  },
  {
    id: "p-legal-risk-api",
    name: "司法风险查询 API",
    delivery: "API",
    serviceVersion: 1,
    description: "司法风险信息查询 API，提交发布审批中。",
    targetUsers: "风控系统",
    assets: [
      { assetId: "asset-judicial-report", assetVersion: 1, usageScope: "涉诉信息", rightId: "right-customer-table-hold", purpose: "风险查询" },
    ],
    status: "待审批",
    apiConfig: { path: "/v1/legal-risk", method: "POST", quotaPerDay: 10000, fields: ["ent_id", "case_count", "risk_level"], region: "全国" },
    operator: "运营人员-何运营",
    owner: "陈审核",
    createdAt: "2026-08-10 09:00:00",
    updatedAt: "2026-08-12 16:00:00",
  },
];

export const defaultProductApprovals: ProductApproval[] = [
  {
    id: "pa-risk-profile-v2",
    productId: "p-risk-profile-api",
    productName: "企业风险画像 API",
    submittedBy: "运营人员-何运营",
    submittedAt: "2026-08-04 09:30:00",
    status: "已通过",
    steps: [
      { name: "资产负责人确认", role: "资产负责人-陈审核", status: "approved", by: "陈审核", at: "2026-08-04 10:00:00", opinion: "模型 v1.2 与司法特征确认无误" },
      { name: "安全审批", role: "安全审批人-吴安全", status: "approved", by: "吴安全", at: "2026-08-04 11:00:00", opinion: "无新增敏感字段，通过" },
    ],
  },
  {
    id: "pa-customer-query-v1",
    productId: "p-customer-query-api",
    productName: "客户经营查询 API",
    submittedBy: "运营人员-何运营",
    submittedAt: "2026-06-20 10:00:00",
    status: "已通过",
    steps: [
      { name: "资产负责人确认", role: "资产负责人-张明", status: "approved", by: "张明", at: "2026-06-20 14:00:00", opinion: "确认" },
      { name: "安全审批", role: "安全审批人-吴安全", status: "approved", by: "吴安全", at: "2026-06-21 09:00:00", opinion: "含敏感字段 mobile，需授权时严格管控" },
    ],
  },
  {
    id: "pa-customer-ops-download-v1",
    productId: "p-customer-ops-download",
    productName: "客户经营分析报告下载",
    submittedBy: "运营人员-何运营",
    submittedAt: "2026-07-20 09:00:00",
    status: "已通过",
    steps: [
      { name: "资产负责人确认", role: "资产负责人-王芳", status: "approved", by: "王芳", at: "2026-07-20 15:00:00", opinion: "确认" },
      { name: "安全审批", role: "安全审批人-吴安全", status: "approved", by: "吴安全", at: "2026-07-21 09:00:00", opinion: "通过" },
    ],
  },
  {
    id: "pa-legal-risk-pending",
    productId: "p-legal-risk-api",
    productName: "司法风险查询 API",
    submittedBy: "运营人员-何运营",
    submittedAt: "2026-08-12 16:00:00",
    status: "待负责人确认",
    steps: [
      { name: "资产负责人确认", role: "资产负责人-陈审核", status: "pending" },
      { name: "安全审批", role: "安全审批人-吴安全", status: "pending" },
    ],
  },
];

export const defaultAuthorizations: Authorization[] = [
  {
    id: "az-risk-system",
    productId: "p-customer-query-api",
    productName: "客户经营查询 API",
    applicant: "风控部-风控系统",
    applicantKind: "内部",
    purpose: "贷款风险审核",
    purposeNote: "贷前调查与贷后风险监控",
    useSystem: "风控决策引擎",
    fields: ["customer_id", "risk_level", "province"],
    quotaPerDay: 1000,
    effectiveFrom: "2026-07-01",
    effectiveTo: "2027-06-30",
    status: "已授权",
    requiresSecurity: true,
    securityStatus: "已通过",
    approvedBy: "张明",
    createdAt: "2026-06-28 10:00:00",
    updatedAt: "2026-06-29 11:00:00",
  },
  {
    id: "az-analyst-download",
    productId: "p-customer-ops-download",
    productName: "客户经营分析报告下载",
    applicant: "业务分析-李梅",
    applicantKind: "内部",
    purpose: "经营分析",
    purposeNote: "华东区 2026 年第二季度经营分析",
    useSystem: "个人账号",
    fields: [],
    region: "华东",
    effectiveFrom: "2026-08-13",
    effectiveTo: "2026-08-15",
    status: "已授权",
    requiresSecurity: false,
    securityStatus: "无需",
    approvedBy: "王芳",
    createdAt: "2026-08-13 08:00:00",
    updatedAt: "2026-08-13 08:30:00",
  },
  {
    id: "az-partner-a-settle",
    productId: "p-ec-region-api",
    productName: "华东区域经营 API",
    applicant: "合作机构A-结算系统",
    applicantKind: "外部",
    purpose: "外部合作结算",
    purposeNote: "华东区域对账结算",
    useSystem: "结算系统",
    fields: ["region", "amount", "order_count"],
    region: "华东",
    quotaPerDay: 2000,
    effectiveFrom: "2025-09-10",
    effectiveTo: "2026-08-31",
    status: "已授权",
    requiresSecurity: true,
    securityStatus: "已通过",
    approvedBy: "王芳",
    createdAt: "2025-09-10 09:30:00",
    updatedAt: "2025-09-11 10:00:00",
  },
  {
    id: "az-partner-a-risk",
    productId: "p-risk-profile-api",
    productName: "企业风险画像 API",
    applicant: "合作机构A-风控系统",
    applicantKind: "外部",
    purpose: "外部合作结算",
    purposeNote: "合作机构对公客户风险审核",
    useSystem: "合作风控平台",
    fields: ["ent_id", "risk_score", "risk_level"],
    quotaPerDay: 500,
    effectiveFrom: "2026-08-01",
    effectiveTo: "2027-07-31",
    status: "已授权",
    requiresSecurity: true,
    securityStatus: "已通过",
    approvedBy: "陈审核",
    createdAt: "2026-07-28 10:00:00",
    updatedAt: "2026-07-29 15:00:00",
  },
  {
    id: "az-market-expired",
    productId: "p-customer-query-api",
    productName: "客户经营查询 API",
    applicant: "市场部-活动系统",
    applicantKind: "内部",
    purpose: "营销推荐",
    purposeNote: "活动人群圈选",
    useSystem: "活动运营平台",
    fields: ["customer_id", "name"],
    quotaPerDay: 500,
    effectiveFrom: "2025-12-01",
    effectiveTo: "2026-06-30",
    status: "已过期",
    requiresSecurity: false,
    securityStatus: "无需",
    approvedBy: "张明",
    createdAt: "2025-11-28 10:00:00",
    updatedAt: "2025-11-29 10:00:00",
  },
  {
    id: "az-risk-revoked",
    productId: "p-customer-query-api",
    productName: "客户经营查询 API",
    applicant: "风控部-旧查询系统",
    applicantKind: "内部",
    purpose: "贷款风险审核",
    purposeNote: "旧系统数据迁移",
    useSystem: "旧风控查询平台",
    fields: ["customer_id", "name", "mobile"],
    quotaPerDay: 200,
    effectiveFrom: "2026-01-01",
    effectiveTo: "2026-12-31",
    status: "已撤销",
    requiresSecurity: true,
    securityStatus: "已通过",
    approvedBy: "张明",
    revokedReason: "大量失败调用（连续 5 小时失败率 > 60%），运营人员撤销授权",
    createdAt: "2025-12-20 10:00:00",
    updatedAt: "2026-08-02 16:00:00",
  },
  {
    id: "az-analytics-pending",
    productId: "p-customer-ops-download",
    productName: "客户经营分析报告下载",
    applicant: "数据分析平台-调度账号",
    applicantKind: "内部",
    purpose: "经营分析",
    purposeNote: "月度经营分析自动取数",
    useSystem: "数据分析平台",
    fields: [],
    region: "全国",
    effectiveFrom: "2026-08-20",
    effectiveTo: "2027-02-19",
    status: "待审批",
    requiresSecurity: false,
    securityStatus: "无需",
    createdAt: "2026-08-13 08:40:00",
    updatedAt: "2026-08-13 08:40:00",
  },
  {
    id: "az-partner-b-pending",
    productId: "p-risk-profile-api",
    productName: "企业风险画像 API",
    applicant: "合作伙伴B-风控系统",
    applicantKind: "外部",
    purpose: "外部合作结算",
    purposeNote: "联合营销客户风控",
    useSystem: "合作方平台",
    fields: ["ent_id", "risk_score"],
    quotaPerDay: 300,
    effectiveFrom: "2026-09-01",
    effectiveTo: "2027-08-31",
    status: "待审批",
    requiresSecurity: true,
    securityStatus: "待安全审批",
    createdAt: "2026-08-12 14:00:00",
    updatedAt: "2026-08-12 14:00:00",
  },
];

export const defaultDownloadTasks: DownloadTask[] = [
  {
    id: "dt-analyst-ec-q2",
    authorizationId: "az-analyst-download",
    productId: "p-customer-ops-download",
    productName: "客户经营分析报告下载",
    requester: "业务分析-李梅",
    fileFormat: "PDF",
    maxDownloads: 2,
    usedDownloads: 1,
    validUntil: "2026-08-15 08:30:00",
    status: "有效",
    masking: "无",
    dataRange: "华东 · 2026Q2",
    serviceVersion: 1,
    assetVersions: ["asset-customer-ops-report#v1"],
  },
  {
    id: "dt-market-expired",
    authorizationId: "az-market-expired",
    productId: "p-customer-query-api",
    productName: "客户经营查询 API",
    requester: "市场部-活动系统",
    fileFormat: "CSV",
    maxDownloads: 1,
    usedDownloads: 0,
    validUntil: "2026-07-01 00:00:00",
    status: "已失效",
    masking: "手机号脱敏",
    dataRange: "全国",
    serviceVersion: 1,
    assetVersions: ["asset-customer-table#v1"],
  },
  {
    id: "dt-partner-a-settle",
    authorizationId: "az-partner-a-settle",
    productId: "p-ec-region-api",
    productName: "华东区域经营 API",
    requester: "合作机构A-结算系统",
    fileFormat: "Excel",
    maxDownloads: 5,
    usedDownloads: 0,
    validUntil: "2026-08-31 23:59:00",
    status: "已失效",
    masking: "金额保留两位小数",
    dataRange: "华东",
    serviceVersion: 1,
    assetVersions: ["asset-ec-region-data#v1"],
  },
];

export const defaultRetention: RetentionPolicy = {
  policyYears: 3,
  frozen: { scope: "2023-06 批次访问审计", reason: "关联未关闭安全调查（调查编号 SEC-2026-0071）" },
};
